#!/usr/bin/env bash
# scripts/setup-env.sh
#
# 幂等地把 FDE 部署所需的 LOOM_* 环境变量写入仓库根目录的 .env。
#
# - 已存在 .env 时先备份成 .env.bak.<时间戳>，再用 awk 删除 LOOM_FERNET_KEY
#   / LOOM_AUTH_USERNAME / LOOM_AUTH_PASSWORD_HASH / LOOM_INSTANCE_ID
#   / LOOM_AUTH_COOKIE_INSECURE_OK / LOOM_DATA_DIR 这几行，再把新值追加到末尾；
#   其他行（如 OPENAI_API_KEY）原样保留。
# - 默认完整模式会写本地测试账号：admin / Admin123456!。
# - --fernet-only 推荐用于 Docker 部署：只写 Fernet / instance / data-dir，
#   管理员账号后续用 `docker compose run --rm fde loom admin init` 初始化到 /data/auth.json。
# - LOOM_FERNET_KEY 与 LOOM_AUTH_PASSWORD_HASH 现场用 Python stdlib 生成，
#   不依赖 bcrypt / passlib 等第三方库。
# - 写入后把 .env 权限收到 600。
#
# 用法：
#   bash scripts/setup-env.sh --fernet-only # 推荐 Docker 部署路径
#   bash scripts/setup-env.sh                # 用默认 admin / Admin123456!
#   PASSWORD='你的密码' bash scripts/setup-env.sh  # 自定义密码

set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE=".env"
USERNAME="${USERNAME:-admin}"
PASSWORD="${PASSWORD:-Admin123456!}"
INSTANCE_ID="${INSTANCE_ID:-local-fde}"
DATA_DIR="${DATA_DIR:-./.loom-data}"
# 本地 http://localhost:18080 调试需要 true；上生产必须改 false 并配 TLS。
COOKIE_INSECURE_OK="${COOKIE_INSECURE_OK:-true}"
FERNET_ONLY=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --fernet-only)
      FERNET_ONLY=true
      shift
      ;;
    -h|--help)
      echo "用法：bash scripts/setup-env.sh [--fernet-only]"
      exit 0
      ;;
    *)
      echo "error: unknown option: $1" >&2
      exit 2
      ;;
  esac
done

if ! command -v python3 >/dev/null 2>&1; then
  echo "error: python3 未安装" >&2
  exit 2
fi

echo "▶ 生成 Fernet 密钥..."
FERNET_KEY=$(python3 -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())' 2>/dev/null) || {
  echo "error: cryptography 模块未安装；先在 .venv 里 'pip install cryptography' 或激活 .venv 再跑此脚本" >&2
  exit 2
}

PASS_HASH=""
if [[ "$FERNET_ONLY" != "true" ]]; then
  echo "▶ 生成 scrypt 密码哈希（账号 ${USERNAME}）..."
  PASS_HASH=$(PASSWORD="$PASSWORD" python3 - <<'PY'
import os, hashlib, base64
pw = os.environ["PASSWORD"].encode()
salt = os.urandom(16)
h = hashlib.scrypt(pw, salt=salt, n=2**14, r=8, p=1, dklen=32, maxmem=128 * 1024 * 1024)
print(f"scrypt$16384$8$1${base64.b64encode(salt).decode()}${base64.b64encode(h).decode()}")
PY
)
fi

if [[ -f "$ENV_FILE" ]]; then
  BACKUP=".env.bak.$(date +%Y%m%d-%H%M%S)"
  cp "$ENV_FILE" "$BACKUP"
  echo "▶ 已备份现有 .env → ${BACKUP}"

  # 删掉 LOOM_* 行（注释行不动）
  TMP=$(mktemp)
  awk '
    /^LOOM_FERNET_KEY=/        {next}
    /^LOOM_AUTH_USERNAME=/     {next}
    /^LOOM_AUTH_PASSWORD_HASH=/{next}
    /^LOOM_INSTANCE_ID=/       {next}
    /^LOOM_AUTH_COOKIE_INSECURE_OK=/ {next}
    /^LOOM_DATA_DIR=/          {next}
    {print}
  ' "$ENV_FILE" > "$TMP"
  mv "$TMP" "$ENV_FILE"
else
  : > "$ENV_FILE"
  echo "▶ 创建新的 .env"
fi

# 追加新值；如尾行不是空行先补一个空行
[[ -s "$ENV_FILE" && "$(tail -c1 "$ENV_FILE" | od -An -c | tr -d ' ')" != "\\n" ]] && echo "" >> "$ENV_FILE"

cat >> "$ENV_FILE" <<EOF

# === FDE auth (generated by scripts/setup-env.sh at $(date '+%Y-%m-%d %H:%M:%S')) ===
LOOM_FERNET_KEY=${FERNET_KEY}
EOF

if [[ "$FERNET_ONLY" != "true" ]]; then
  cat >> "$ENV_FILE" <<EOF
LOOM_AUTH_USERNAME=${USERNAME}
LOOM_AUTH_PASSWORD_HASH=${PASS_HASH}
EOF
fi

cat >> "$ENV_FILE" <<EOF
LOOM_INSTANCE_ID=${INSTANCE_ID}
LOOM_DATA_DIR=${DATA_DIR}
# 本地 HTTP 调试用；公网部署务必改 false 并配反代 + TLS
LOOM_AUTH_COOKIE_INSECURE_OK=${COOKIE_INSECURE_OK}
EOF

chmod 600 "$ENV_FILE"

echo ""
echo "✓ 已写入 ${ENV_FILE}（权限 600）"
echo ""
echo "下一步："
if [[ "$FERNET_ONLY" == "true" ]]; then
  echo "  docker compose build"
  echo "  docker compose run --rm fde loom admin init"
  echo "  docker compose up -d"
  echo "  curl http://localhost:18080/v1/health   # 期望 {\"ok\":true}"
else
  echo "  docker compose up -d --build"
  echo "  curl http://localhost:18080/v1/health   # 期望 {\"ok\":true}"
  echo "  open http://localhost:18080             # 登录 ${USERNAME} / ${PASSWORD}"
fi
echo ""
if [[ "$COOKIE_INSECURE_OK" == "true" ]]; then
  echo "⚠ 提醒：LOOM_AUTH_COOKIE_INSECURE_OK=true 仅为本地 HTTP 调试。"
  echo "        公网部署前请改 false 并在 nginx/traefik 终结 TLS。"
fi
